#!/bin/sh

# release test, only builds the tgz file

# clean up dist directory
#rm -rf ~/ipython/dist/*

# build source distros
cd ~/ipython/ipython
#./setup.py sdist --formats=gztar
./setup.py sdist --formats=gztar bdist --formats=rpm
