#!/usr/bin/env python
# Call with --help for details

try:
    from snakeoil import oilrun
except ImportError:
    # If running the script from a non-installed snakeoil.
    import oilrun

oilrun.main()
