#!/usr/bin/env python
# Call with --help for details

try:
    from snakeoil import oildoc
except ImportError:
    # If running the script from a non-installed snakeoil.
    import oildoc

oildoc.main_py2doctest()
