#!/usr/bin/env python
# Call with --help for details

try:
    from snakeoil import oilscript
except ImportError:
    # If running the script from a non-installed snakeoil.
    import oilscript
    
oilscript.main()
