#!/usr/bin/env python
"""Update IPython's private copy of Twisted Web2.

Usage:
  update_web2

You MUST run this from within your Twisted SVN directory, where web2 lives.


WARNING: This is a tool for IPython developers only!!!  Don't use this if you
don't already know what  it means and does.
"""

# Make sure we CAN get a current  web2 from ipython
from ipython1.external.twisted import web2

# Move along
import os
import tempfile

xsys = os.system

web2_dir = os.path.split(web2.__file__)[0]

tmp_dir = tempfile.mkdtemp()

xsys('svn export web2 %s/web2' % tmp_dir)
os.chdir(tmp_dir+'/web2')
xsys("rpl -R -d -x'.py' twisted.web2 ipython1.external.twisted.web2 *")
xsys("diff -x '*.pyc' -x '.svn' -x 'test' -x '*~' -ur %s .  > %s/web2.patch" %
     (web2_dir,web2_dir))
os.chdir(web2_dir)
xsys('patch -p0 < web2.patch')
xsys('rm -rf %s' % tmp_dir)
