#!/usr/bin/env python
"""The ipython controller.
"""

#-------------------------------------------------------------------------------
#       Copyright (C) 2005  Fernando Perez <fperez@colorado.edu>
#                           Brian E Granger <ellisonbg@gmail.com>
#                           Benjamin Ragan-Kelley <benjaminrk@gmail.com>
#
#  Distributed under the terms of the BSD License.  The full license is in
#  the file COPYING, distributed as part of this software.
#-------------------------------------------------------------------------------

import sys, os
from optparse import OptionParser

from twisted.internet import reactor
from twisted.python import log

from ipython1.kernel import controllerservice
from ipython1.kernel.multiengine import IMultiEngine
from ipython1.kernel.task import ITaskController
import ipython1.config.api as config

taskConfig = config.getConfigObject('taskcontroller')

def main(logfile):
    if logfile:
        logfile = logfile + str(os.getpid()) + '.log'
        try:
            openLogFile = open(logfile, 'w')
        except:
            openLogFile = sys.stdout
    else:
        openLogFile = sys.stdout
    log.startLogging(openLogFile)
    
    # Create and configure the core ControllerService
    cs = controllerservice.ControllerService()
    
    # Start listening for engines  
    efac = taskConfig.engineServerProtocolInterface(cs)
    reactor.listenTCP(
        port=taskConfig.listenForEnginesOn['port'],
        factory=efac,
        interface=taskConfig.listenForEnginesOn['ip'])
        
    # Start listening for ITaskController clients
    taskController = ITaskController(cs)
    for ci in taskConfig.taskClientInterfaces:
        fac = ci['interface'](taskController)
        reactor.listenTCP(
            port=ci['port'],
            factory=fac,
            interface=ci['ip'])
            
    multiEngine = IMultiEngine(cs)
    for ci in taskConfig.clientInterfaces:
        fac = ci['interface'](multiEngine)
        reactor.listenTCP(
            port=ci['port'],
            factory=fac,
            interface=ci['ip'])
        
    # Start the controller service and set things running
    cs.startService()
    reactor.run()

def start():
    parser = OptionParser()
    parser.set_defaults(logfile='')
        
    parser.add_option("--engine-port", type="int", dest="engineport",
        help="the TCP port the controller will listen on for engine connections")
    parser.add_option("--engine-ip", type="string", dest="engineip",
        help="the TCP ip address the controller will listen on for engine connections")
    parser.add_option("-l", "--logfile", type="string", dest="logfile",
        help="log file name (default is stdout)")
        
    # Configuration files and profiles
    parser.add_option("-p", "--profile", type="string", dest="profile",
        help="the name of a profile")
    parser.add_option("--rcfile", type="string", dest="rcfile",
        help="the name of a configuration file")
    parser.add_option("--ipythondir", type="string", dest="ipythondir",
        help="look for config files and profiles in this directory")
    (options, args) = parser.parse_args()
          
    # Configuration files and profiles
    if options.profile and not options.rcfile:
        config.updateConfigWithProfile('ipcontroller', options.profile, options.ipythondir)
    elif options.rcfile and not options.profile:
        config.updateConfigWithFile(options.rcfile, options.ipythondir)
    else:
        config.updateConfigWithFile('ipcontrollerrc.py', options.ipythondir)
        
    # Update withh command line options
    if options.engineip is not None:
        taskConfig.listenForEnginesOn['ip'] = options.engineip
    if options.engineport is not None:
        taskConfig.listenForEnginesOn['port'] = options.engineport
        
    main(options.logfile)
    
    
if __name__ == "__main__":
    start()
