#!/usr/bin/env python

from twisted.spread import pb
from twisted.internet import reactor
from IPython.genutils import clock, clock2

def gotObject(object):
    print "Got Root object:", object, clock()
    
    object.callRemote("put",10,10).addCallback(halt)
    #object.callRemote("restart_engine")
    
def halt(data):
    print clock()
    #reactor.stop()
   
def gotData(data):
    pass
    #print 'server sent:', data
    #reactor.stop()
    
def gotError(reason):
    reason.printTraceback()
    
def gotNoObject(reason):
    print "no object:",reason
    reactor.stop()

factory = pb.PBClientFactory()
reactor.connectTCP("127.0.0.1",12023, factory)
factory.getRootObject().addCallbacks(gotObject,gotNoObject)
reactor.run()
