#!/usr/bin/env python

#*****************************************************************************
#       Copyright (C) 2005  Fernando Perez <fperez@colorado.edu>
#                           Brian E Granger <ellisonbg@gmail.com>
#                           Benjamin Ragan-Kelly <<benjaminrk@gmail.com>>
#
#  Distributed under the terms of the BSD License.  The full license is in
#  the file COPYING, distributed as part of this software.
#*****************************************************************************

from twisted.spread import pb
from twisted.internet import reactor
from IPython.genutils import clock, clock2

def gotObject(object):
    print "Got Root object:", object, clock()
    
    object.callRemote("put",10,10).addCallback(halt)
    #object.callRemote("restart_engine")
    
def halt(data):
    print clock()
    #reactor.stop()
   
def gotData(data):
    pass
    #print 'server sent:', data
    #reactor.stop()
    
def gotError(reason):
    reason.printTraceback()
    
def gotNoObject(reason):
    print "no object:",reason
    reactor.stop()

factory = pb.PBClientFactory()
reactor.connectTCP("127.0.0.1",12023, factory)
factory.getRootObject().addCallbacks(gotObject,gotNoObject)
reactor.run()
