#!/usr/bin/env python
"""The IPython Kernel Engine.

To start the engine on port 9999 use:

ipengine -p 9999
"""
#*****************************************************************************
#       Copyright (C) 2005  Brian Granger, <bgranger@scu.edu>
#                           Fernando Perez. <fperez@colorado.edu>
#
#  Distributed under the terms of the BSD License.  The full license is in
#  the file COPYING, distributed as part of this software.
#*****************************************************************************

import sys
from optparse import OptionParser

from twisted.internet import reactor
from twisted.spread import pb
from twisted.python import log

import ipython1.kernel.coreservice as cs

def main(port):
    log.startLogging(sys.stdout)
    ipcore = cs.CoreService()
    ipcore.startService()
    reactor.listenTCP(port, 
        pb.PBServerFactory(cs.IPerspectiveCore(ipcore)),
        interface = '127.0.0.1')
    reactor.run()

def start(port=12023):
    parser = OptionParser()
    parser.set_defaults(port=port)
    parser.add_option("-p", "--port", type="int", dest="port",
        help="the TCP port the kernel will listen on")
    (options, args) = parser.parse_args()
    print "Starting the kernel on port %i" % options.port
    main(options.port)
    
if __name__ == "__main__":
    start()
