#!/usr/bin/env python
"""The IPython Kernel Engine using perspective broker.

To start the engine on port 9999 use:

ipenginepb -p 9999 -c '127.0.0.1'
"""
#*****************************************************************************
#       Copyright (C) 2005  Brian Granger, <bgranger@scu.edu>
#                           Fernando Perez. <fperez@colorado.edu>
#
#  Distributed under the terms of the BSD License.  The full license is in
#  the file COPYING, distributed as part of this software.
#*****************************************************************************

import sys
from optparse import OptionParser

from twisted.internet import reactor, error
from twisted.spread import pb
from twisted.python import log

from ipython1.kernel import engineservice, enginepb


def main(controller, port):
    log.startLogging(sys.stdout)
    service = engineservice.EngineService()
    service.startService()
    d = reactor.connectTCP(controller, port,
        enginepb.PBEngineClientFactory(service))
    reactor.run()

def start(port=10201, controller = '127.0.0.1'):
    parser = OptionParser()
    parser.set_defaults(port=port)
    parser.set_defaults(controller=controller)
    parser.add_option("-p", "--port", type="int", dest="port",
        help="the TCP port the controller listens on")
    parser.add_option("-c", "--controller", type="str", dest="host",
        help="the address of the controller")
    (options, args) = parser.parse_args()
    print "Connecting the engine to %s:%i" % (options.controller,options.port)
    main(options.controller, options.port)
    
if __name__ == "__main__":
    start()
