#!/usr/bin/env python
# encoding: utf-8
"""
netstring.py

Created by Brian Granger on 2006-08-09.
"""

import sys
import os
import socket

def main(host, port, listen):
    if listen:
        s = socket.socket()
        s.bind((host, port))
        s.listen(1)
        clientSock, clientAddr = s.accept()
    else:
        
    while True:
        
def start():
    parser = OptionParser()
    parser.set_defaults(port=10104)
    parser.add_option('-h', '--host', type='str', dest='host')
    parser.add_option('-p', '--port', type='int', dest='port')
    parser.add_options('-l', '--listen', action='store_true', dest='listen',
        default=True)
    (options, args) = parser.parse_args()
    main(options.host, options.port, options.listen)

if __name__ == '__main__':
    start()

