#!/usr/bin/env python
# encoding: utf-8
"""
netstring.py

Created by Brian Granger on 2006-08-09.
"""

#*****************************************************************************
#       Copyright (C) 2005  Fernando Perez <fperez@colorado.edu>
#                           Brian E Granger <ellisonbg@gmail.com>
#                           Benjamin Ragan-Kelly <<benjaminrk@gmail.com>>
#
#  Distributed under the terms of the BSD License.  The full license is in
#  the file COPYING, distributed as part of this software.
#*****************************************************************************

import sys
import os
import socket

def main(host, port, listen):
    if listen:
        s = socket.socket()
        s.bind((host, port))
        s.listen(1)
        clientSock, clientAddr = s.accept()
    else:
        
def start():
    parser = OptionParser()
    parser.set_defaults(port=10104)
    parser.add_option('-h', '--host', type='str', dest='host')
    parser.add_option('-p', '--port', type='int', dest='port')
    parser.add_options('-l', '--listen', action='store_true', dest='listen',
        default=True)
    (options, args) = parser.parse_args()
    main(options.host, options.port, options.listen)

if __name__ == '__main__':
    start()

